### ISSUE TITLE
php run.php

### ISSUE THREAD

**Issue by hkzj0571** [metowolf/JumpJumpHelper#1]
PHP Warning:  imagecreatefrompng(screen.png): failed to open stream: No such file or directory in D:\jump\run.php on line 111

Warning: imagecreatefrompng(screen.png): failed to open stream: No such file or directory in D:\jump\run.php on line 111
PHP Warning:  imagesx() expects parameter 1 to be resource, boolean given in D:\jump\run.php on line 17

Warning: imagesx() expects parameter 1 to be resource, boolean given in D:\jump\run.php on line 17
PHP Warning:  imagesy() expects parameter 1 to be resource, boolean given in D:\jump\run.php on line 18

**Comment by metowolf** [comment]
目录下是否有 `screen.png` 文件生成

**Comment by hkzj0571** [comment]
没有。我是windows

**Comment by metowolf** [comment]
那么你可能得打开 cmd，看看这两句命令能否正常执行
```
adb shell screencap -p /sdcard/screen.png
adb pull /sdcard/screen.png
```

如果不能的话，需要先安装 adb 驱动

**Comment by hkzj0571** [comment]
adb server is out of date.  killing...
* daemon started successfully *
error: device not found

**Comment by metowolf** [comment]
看起来是找不到设备，那就得检查一下设备的调试模式是否打开，或者更简单的就尝试连接上手机助手来解决

**Comment by hkzj0571** [comment]
连不上设备，全开了，手机助手怎么弄
