### ISSUE TITLE
排行榜中不显示刷出来的分数，微信防作弊了，怎么破啊

### ISSUE THREAD

**Issue by bing15** [metowolf/JumpJumpHelper#15]
微信防作弊了，怎么破啊，刷了好几次，用了好几种方法还是不行。

**Comment by ChristianSwift** [comment]
把adb指令那边的固定x1,x2,y1,y2改成random值，sleep也加个随机参量，不过好像进了VAC黑名单的貌似就出不来了

**Comment by Cp0204** [comment]
楼上正解，实测加了rand有效，已pull

**Comment by metowolf** [comment]
看起来微信校验了触屏数据
