### ISSUE TITLE
你好，提示我没有定义x,y变量

### ISSUE THREAD

**Issue by baozinull** [metowolf/JumpJumpHelper#2]
```
#00000: 
Notice: Undefined variable: x in D:\bzwamp\Apache24\htdocs\php_work\JumpJumpHelper-master\run.php on line 126

Notice: Undefined variable: y in D:\bzwamp\Apache24\htdocs\php_work\JumpJumpHelper-master\run.php on line 126

Notice: Undefined variable: mid in D:\bzwamp\Apache24\htdocs\php_work\JumpJumpHelper-master\run.php on line 51

Notice: Undefined variable: mid in D:\bzwamp\Apache24\htdocs\php_work\JumpJumpHelper-master\run.php on line 51
```

**Comment by metowolf** [comment]
可以先去看看目录下的 `screen.png` 是否是游戏画面，把这个图片传上来看看

**Comment by baozinull** [comment]
是游戏画面，但是会一张一张的覆盖，直到游戏结束。但是我的screen目录没有图片。

**Comment by metowolf** [comment]
通常不至于第一张就报错，报错的原因是因为找不到坐标，所以可以把报错后的 screen.png 传上 issue 我看看原因

**Comment by baozinull** [comment]
![screen](https://user-images.githubusercontent.com/34702523/34466766-5825d0fa-ef1a-11e7-8461-76969d190802.png)
你好，是这一张。

**Comment by baozinull** [comment]
还在不？大神，我这哪里出错了，能帮忙解决一下吗？

**Comment by yangguangwuwu** [comment]
我证明 可以用
 开发者模式 usb调试要开 还有触摸模拟

**Comment by yangguangwuwu** [comment]
代码是没问题的 只是你们姿势不对

**Comment by baozinull** [comment]
开发者模式开了，adb devices也显示有设备。触摸模拟，我手动输入命令的话小人可以动。还是不知道哪里有问题。。。

**Comment by metowolf** [comment]
这个问题已经确认，是屏幕分辨率没有做兼容，等我修复

**Comment by baozinull** [comment]
好滴，感谢。

**Comment by metowolf** [comment]
@baozinull 将配置中的 `BODY_WIDTH` 设置成 50，然后再测试，`PRESS_TIME` 根据实际表现调节

**Comment by baozinull** [comment]
又报错了，每行有个Error: Invalid arguments for command: swipe usage: input ... input text input keyevent input [touchscreen|touchpad] tap input [touchscreen|touchpad] swipe input trackball press input trackball roll

**Comment by metowolf** [comment]
@baozinull 大概是触控位置超出屏幕了，已调整

**Comment by baozinull** [comment]
还是报这个错误，会不会是我的问题。2333...

**Comment by metowolf** [comment]
你说到手动输入命令能跳动，试试在 `run.php` 中修改成那个命令参数

**Comment by baozinull** [comment]
adb shell input swipe 320 410 320 410 790
这个命令，我在控制台手动输入的时候只能有4个参数，5个参数就报上面那个错了。然后我把代码中的$time删掉，可以动了，但是幅度很小。我又去改了压力度参数，感觉没什么变化。

**Comment by metowolf** [comment]
你的机型是不是 android 4.0 或以下
低版本貌似是不支持长触屏的

**Comment by baozinull** [comment]
Android 4.2.2，那好滴。我明天换个手机试试。辛苦楼主
