### ISSUE TITLE
截图都有了，就是不跳动

### ISSUE THREAD

**Issue by zaite** [metowolf/JumpJumpHelper#5]
![qq 20180101233646](https://user-images.githubusercontent.com/22079456/34468862-ce192c44-ef4c-11e7-8e82-8c1222a3809e.png)

**Comment by zaite** [comment]
调试和模拟点击都已经开启

**Comment by zaite** [comment]
手机用的是 小米4x

**Comment by metowolf** [comment]
尝试在 cmd 输入 `adb shell input swipe 400 400 400 400 200` 看是否有反映

**Comment by zaite** [comment]
adb shell input swipe 400 400 400 400 200 敲入指令是有反应的，运行run.php没有反应

**Comment by yaoshanliang** [comment]
同不跳动

**Comment by metowolf** [comment]
贴出几条控制台记录我看看

**Comment by yaoshanliang** [comment]
![image](https://user-images.githubusercontent.com/5028569/34468940-9b78cbe4-ef4e-11e7-8b1f-0fcef1fb822e.png)

**Comment by metowolf** [comment]
试一下这条命令能否跳动 `adb shell input swipe 320 410 320 410 790`

**Comment by zaite** [comment]
@metowolf adb shell input swipe 320 410 320 410 790  输入命令可以跳动

**Comment by metowolf** [comment]
这就很诡异了，你修改文件中的 press 函数

```
function press($time) {
	system('adb shell input swipe 320 410 320 410 ' . $time);
	echo 'adb shell input swipe 320 410 320 410 ' . $time . PHP_EOL;
}
```

运行后，贴一下日志

**Comment by zaite** [comment]
@metowolf 

function press($time) {
	system('adb shell input swipe 320 410 320 410 ' . $time);
	echo 'adb shell input swipe 320 410 320 410 ' . $time . PHP_EOL;
}
更换这个后可以跳动，只不过不准确

**Comment by metowolf** [comment]
机型不同  
如果距离不对需要调一下 `PRESS_TIME` 参数  
如果发现定位点有问题，根据棋子的宽度调节一下 `BODY_WIDTH`

**Comment by zaite** [comment]
@metowolf ok 谢谢大神
