### ISSUE TITLE
失败案例汇总

### ISSUE THREAD

**Issue by metowolf** [metowolf/JumpJumpHelper#8]
大家如果发现有失败的识别案例，可以去 screen 目录下找到该图片，上传到这里来。
**注意要上传原图，而不是截图或压缩过的图片**

修复信息我会直接 edit 在图片下方

**Comment by TangoEvol** [comment]
本人用的 三星s8   屏幕（2k分辨率）直线没有问题  一拐弯 就跳失败了

**Comment by seekcx** [comment]
![image](https://user-images.githubusercontent.com/8244814/34473577-9f476454-efaf-11e7-9bd2-94442adffaab.png)
目测是被影子干扰了

----

 - #f8328ab 修复棋子与棋盘过于接近，无法取得横坐标

**Comment by seekcx** [comment]
![image](https://user-images.githubusercontent.com/8244814/34473906-5d19778a-efb3-11e7-8c3e-954a941a46d2.png)

----

答复：修改 `BODY_WIDTH` 参数为 49 即可

**Comment by TangoEvol** [comment]
![screen scan](https://user-images.githubusercontent.com/17248808/34473946-bc5647b4-efb3-11e7-8515-9ca75cc8746b.png)

----

答复：S8 的曲面侧屏干扰到了，可以先临时关掉

**Comment by kangliuchang** [comment]
![1 f3e9rd 4 fzxeqfrsa m](https://user-images.githubusercontent.com/20853754/34476130-2fe994a0-efc9-11e7-89ae-dc67754368fd.png)
![2ex40t osx9bfnnjvel 0](https://user-images.githubusercontent.com/20853754/34476131-34773bd0-efc9-11e7-8dbf-99000860029a.png)
哥哥, 手机已经联好没问题了 ,这里是哪里的问题, 总是报错
![image](https://user-images.githubusercontent.com/20853754/34476165-57258eca-efc9-11e7-9fe1-3cb332c12450.png)

**Comment by TangoEvol** [comment]
![00006](https://user-images.githubusercontent.com/17248808/34476963-783f17c8-efd0-11e7-9305-4a62cd84aa69.png)
好友的头像好像是有 误导这个跳的地方

**Comment by linphy** [comment]
![00150](https://user-images.githubusercontent.com/3156110/34483455-8b5f49a8-eff9-11e7-8f42-e272a5e48071.png)
![00151](https://user-images.githubusercontent.com/3156110/34483456-8b91aeca-eff9-11e7-81d0-7d28ccf3c145.png)

**Comment by baozinull** [comment]
![screen scan](https://user-images.githubusercontent.com/34702523/34508413-fe566d3a-f079-11e7-8bc0-053fcacbe8e2.png)

**Comment by baozinull** [comment]
![00043](https://user-images.githubusercontent.com/34702523/34508548-b0526308-f07b-11e7-89f4-3ed004b79a8e.png)
![00044](https://user-images.githubusercontent.com/34702523/34508550-b583a0da-f07b-11e7-934c-9c5fdd39da8d.png)


----

答复：识别是正确的，应该是计算时间上有偏差

**Comment by Tinywan** [comment]
##  配置参数：`define('PRESS_TIME', 4.99950169);`
![00004](https://user-images.githubusercontent.com/14959876/34511707-5aa3e69e-f098-11e7-8060-f81ef70c5e85.png)

 ----

答复：没有发现识别的问题啊，这个大概是参数设置不对

**Comment by tianhuo1990** [comment]
![00013](https://user-images.githubusercontent.com/22310074/34548102-e96799c8-f13a-11e7-8f91-c6c3da9060b4.png)

----

答复：临时关闭屏幕右侧的侧屏功能

**Comment by lesteryou** [comment]
[https://imgsa.baidu.com/forum/w%3D580/sign=d0b2d0ef38fa828bd1239debcd1e41cd/1d1e200fd9f9d72a0cd544f7df2a2834359bbb7d.jpg](url)
[https://imgsa.baidu.com/forum/w%3D580/sign=866093095c2c11dfded1bf2b53256255/bdf3bc11728b47105daba926c8cec3fdfd032322.jpg](url)
[https://imgsa.baidu.com/forum/w%3D580/sign=f666c8368113632715edc23ba18da056/4042c812c8fcc3ce24449dd99945d688d53f2022.jpg](url)

**Comment by lesteryou** [comment]
https://imgsa.baidu.com/forum/w%3D580/sign=f666c8368113632715edc23ba18da056/4042c812c8fcc3ce24449dd99945d688d53f2022.jpg

**Comment by zyz102218** [comment]
这里出现了识别错误
![00005](https://user-images.githubusercontent.com/32035515/34829108-96e3a9e0-f71a-11e7-9e1c-e41db78f33de.png)

**Comment by zyz102218** [comment]
这里也出了问题
![00032](https://user-images.githubusercontent.com/32035515/34829445-ad98e44c-f71b-11e7-9b89-82b56862935a.png)

**Comment by Mr-houzi** [comment]
@Boygad 手机虽然连接了电脑，但是电脑不一定能成功识别手机。
1.检查一下通过电脑资源管理器能否访问手机储存
2.检查USB模式（PTP或者MTP）
